[package]
name = "rusty_ladders"
version = "0.1.0"
edition = "2021"


[dependencies]
fastrand = "2.1"
rand = { version = "0.8.5", features = ["small_rng"] }

[profile.release]
debug = true
lto = "fat"
